# Generated by Django 5.1.8 on 2025-05-20 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hostelbooking',
            name='student_photo',
        ),
    ]
