# Generated by Django 5.1.8 on 2025-05-23 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0006_hostelmonthlyinvoice'),
    ]

    operations = [
        migrations.CreateModel(
            name='HostelFeeSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monthly_fee', models.DecimalField(decimal_places=2, default=1500.0, max_digits=8)),
                ('deposit', models.DecimalField(decimal_places=2, default=2000.0, max_digits=8)),
            ],
        ),
    ]
