# Generated by Django 5.1.8 on 2025-05-28 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0007_hostelfeesetting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostelroom',
            name='room_number',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
