# Generated by Django 5.1.8 on 2025-06-20 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0008_alter_hostelroom_room_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostelbooking',
            name='purpose_of_joining',
            field=models.TextField(default='', help_text='For which study you want to join the hostel?'),
        ),
    ]
