# Generated by Django 5.1.8 on 2025-06-24 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0009_hostelbooking_purpose_of_joining'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostelbed',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
