# Generated by Django 5.1.8 on 2025-07-09 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0010_hostelbed_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostelbed',
            name='bed_number',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='hostelroom',
            name='room_number',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
