# Generated by Django 5.1.8 on 2025-07-18 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0011_alter_hostelbed_bed_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostelbooking',
            name='aadhaar_back_photo',
            field=models.ImageField(upload_to='profile_photos/'),
        ),
        migrations.AlterField(
            model_name='hostelbooking',
            name='aadhaar_front_photo',
            field=models.ImageField(upload_to='profile_photos/'),
        ),
    ]
