# Generated by Django 5.1.8 on 2025-07-22 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0012_alter_hostelbooking_aadhaar_back_photo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostelmonthlyinvoice',
            name='invoice_expired',
            field=models.BooleanField(default=False),
        ),
    ]
