# Generated by Django 5.1.8 on 2025-07-27 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0013_hostelmonthlyinvoice_invoice_expired'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostelbooking',
            name='end_date',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
