# Generated by Django 5.1.8 on 2025-08-03 20:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0014_hostelbooking_end_date'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HostelBookingHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previous_room', models.CharField(max_length=50)),
                ('previous_bed', models.CharField(max_length=50)),
                ('new_room', models.CharField(max_length=50)),
                ('new_bed', models.CharField(max_length=50)),
                ('changed_on', models.DateTimeField(auto_now_add=True)),
                ('change_type', models.CharField(default='switch', max_length=50)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='HostelSwitchRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('current_booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='switch_requests', to='hostel.hostelbooking')),
                ('mutual_booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mutual_switch_requests', to='hostel.hostelbooking')),
                ('requested_bed', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requested_switches', to='hostel.hostelbed')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hostel_switch_requests', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
