# Generated by Django 5.1.8 on 2025-08-08 18:19

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0015_hostelbookinghistory_hostelswitchrequest'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HostelBookingHistory',
            new_name='HostelBookingSwitchHistory',
        ),
    ]
