# Generated by Django 5.1.8 on 2025-08-09 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0016_rename_hostelbookinghistory_hostelbookingswitchhistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostelswitchrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
    ]
