# Generated by Django 5.1.8 on 2025-08-09 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0017_alter_hostelswitchrequest_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostelswitchrequest',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
    ]
