# Generated by Django 5.1.8 on 2025-08-11 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0018_hostelswitchrequest_remarks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hostelswitchrequest',
            name='current_booking',
        ),
        migrations.RemoveField(
            model_name='hostelswitchrequest',
            name='mutual_booking',
        ),
        migrations.RemoveField(
            model_name='hostelswitchrequest',
            name='requested_bed',
        ),
        migrations.RemoveField(
            model_name='hostelswitchrequest',
            name='student',
        ),
        migrations.DeleteModel(
            name='HostelBookingSwitchHistory',
        ),
        migrations.DeleteModel(
            name='HostelSwitchRequest',
        ),
    ]
