# Generated by Django 5.1.8 on 2025-08-12 17:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0019_remove_hostelswitchrequest_current_booking_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HostelAvailableSwitchHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('approved', 'Approved'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], max_length=20)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='available_switch_history', to='hostel.hostelbooking')),
                ('from_bed', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='hostel.hostelbed')),
                ('to_bed', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='hostel.hostelbed')),
            ],
        ),
        migrations.CreateModel(
            name='HostelAvailableSwitchRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hostel_available_switch_approver', to=settings.AUTH_USER_MODEL)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='available_switch_requests', to='hostel.hostelbooking')),
                ('target_bed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_switch_requests', to='hostel.hostelbed')),
            ],
        ),
        migrations.CreateModel(
            name='HostelMutualSwitchHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('approved', 'Approved'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], max_length=20)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('booking_a', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='hostel.hostelbooking')),
                ('booking_b', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='hostel.hostelbooking')),
                ('from_bed_a', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='hostel.hostelbed')),
                ('from_bed_b', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='hostel.hostelbed')),
                ('to_bed_a', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='hostel.hostelbed')),
                ('to_bed_b', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='hostel.hostelbed')),
            ],
        ),
        migrations.CreateModel(
            name='HostelMutualSwitchRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hostel_mutual_switch_approver', to=settings.AUTH_USER_MODEL)),
                ('partner_booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='incoming_mutual_requests', to='hostel.hostelbooking')),
                ('requester_booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mutual_requests', to='hostel.hostelbooking')),
            ],
        ),
    ]
